stages:
  - install
  - run

image: node:latest

default:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    when: 'on_success'
    policy: push

install:
  stage: install
  script: 
    - npm ci
  rules:
    - changes:
        - package-lock.json
  cache:
    policy: push

run:
  stage: run
  script:
    - npm run good
  cache:
    policy: pull