name: Deploy Lambda using Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: read

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
  TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
  TF_VAR_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.NOTIFICATIONS_BOT_TOKEN }}
  TF_VAR_NOTIFICATIONS_BOT_USERNAME: ${{ vars.NOTIFICATIONS_BOT_USERNAME }}
  TF_VAR_ADMIN_BOT_USERNAME: ${{ vars.ADMIN_BOT_USERNAME }}
  TF_VAR_ADMIN_BOT_TOKEN: ${{ secrets.ADMIN_BOT_TOKEN }}
  TF_VAR_ADMIN_BOT_SECRET_TOKEN: ${{ secrets.ADMIN_BOT_SECRET_TOKEN }}
  TF_VAR_ADMIN_BOT_OWNER_ID: ${{ vars.ADMIN_BOT_OWNER_ID }}
  TF_VAR_HEALTH_CHAT_ID: ${{ vars.HEALTH_CHAT_ID }}
  TF_VAR_DATABASE_USER: ${{ vars.DATABASE_USER }}
  TF_VAR_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  TF_VAR_DATABASE_HOST: ${{ vars.DATABASE_HOST }}
  TF_VAR_DATABASE_PORT: ${{ vars.DATABASE_PORT }}
  TF_VAR_DATABASE_NAME: ${{ vars.DATABASE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yagelhayun'

      - name: Install Lambda dependencies
        working-directory: lambda
        run: npm ci --omit=dev --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials (OIDC role assumption)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Authenticator
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.7.0'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
